[build]
  base = "nextjs-exigent-upgrade"
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@className/plugin-nextjs"

[build.environment]
  NODE_VERSION = "21"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

