[build]
  base = "nextjs-exigent-upgrade"
  command = "npm run build"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[build.environment]
  NODE_VERSION = "21"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

